[package]
name = "pa-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "The prime-agent binary."

[dependencies]
pa-types = { path = "../pa-types" }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[[bin]]
name = "prime-agent"
path = "src/main.rs"
